name: Deploy to EC2

on:
  push:
    branches:
      - main  # ✅ 여기 중요: main 브랜치 기준!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd be
            ps aux | grep java | grep -v grep | awk '{print $2}' | xargs -r kill -9
            git pull origin main
            ./gradlew build -x test
            rm -f nohup.out
            export $(cat .env | xargs)
            nohup java -jar build/libs/demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=main &
          EOF
